name = "Noir"
grammar = "noir"
path_suffixes = ["nr"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
autoclose_before = ";:.,=}])> \n\t"
word_characters = ["_"]

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "<", end = ">", close = false, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
